### ISSUE TITLE
request: ability to disable file creation

### ISSUE THREAD

**Issue by hugomallet** [honarpour/serverless-export-outputs#5]
Hi,

I would like to disable the plugin depending on a variable (usually the stage).

For example:
```yaml
custom: 
    exportOutputs: false
```
or
```yaml
custom: 
    exportOutputs: 
        enabled: false
        include: ...
```

This could be used using stage option :
```yaml
custom: 
    exportOutputsEnabled: 
        dev: true
    exportOutputs: 
        enabled: ${self:custom.exportOutputsEnabled.${opt:stage}, false}
        include: ...
```
