### ISSUE TITLE
Cannot override output options only

### ISSUE THREAD

**Issue by wiggisser** [honarpour/serverless-export-outputs#9]
The moment I try to override the output file and format, I have to specify also an array for include, otherwise my output file is empty. Looking at the docs (see the <<<<<< marker)

```
custom:
  exportOutputs:
    include: # if not provided, all outputs are exported  <<<<<<<
      - OutputKeyName
      - AnotherOutputKeyName
      - CustomOutput: value # add custom key/value to exports
    handler: scripts/env.js # script to process outputs
    output:
      file: ./.env # file path and name relative to root
      format: toml # toml, yaml/yml, json
```

I'd expect something like

```yaml
custom:
  exportOutput:
    output:
      file: ./env.json
      format: json
```

to create the `env.json` file with all outputs, but instead the file does not contain a single key, but just an empty object, unless I specify also the `include`
